---
title: "WW proj performance examination"
author: "Warsame Yusuf"
date: "13/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
## run ott_projections() in short_term_projections.R to generate data for plots
# load library, packages, functions, data
library(tidyverse)
library(ggplot2)
library(EpiNow2)
library(stringr)
library(purrr)
library(lubridate)
library(plotly)
library(RColorBrewer)
library(zoo)
source("../R/epinow_functions.R")
source("../R/wastewater.R")
source("../R/observed_data.R")

ww_data <-
  read.csv("https://raw.githubusercontent.com/Big-Life-Lab/PHESD/main/Wastewater/Ottawa/Data/wastewater_virus.csv")

ww_clean <- wastewater_prep(ww_data) %>%
  select(date, N1_N2_avg, N1_N2_avg_clean) %>%
  mutate(date = as.Date(date))

# Set reporting delay, generation time, incubation period for simulation
reporting_delay <- NULL
generation_time <-
  get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
incubation_period <-
  get_incubation_period(disease = "SARS-CoV-2", source = "lauer")
```

# WW Projections

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Examine ww projections during Mar-Apr 2021 surge
ww_forecast <- short_term_forecast(
    data = ww_clean,
    input = "N1_N2_avg_clean",
    start_date = "2021-12-01",
    input_multiplier = 1000000,
    omit_last_date = FALSE,
    generation_time = generation_time,
    incubation_period = incubation_period,
    reporting_delay = reporting_delay,
    output = "both"
)

ww_normalized <- ww_clean %>%
  mutate(N1_N2_avg_clean = N1_N2_avg_clean*1000000)

short_term_plot(
  projections = ww_forecast[[1]],
  obs_data = ww_normalized,
  obs_column = "N1_N2_avg_clean",
  forecast_type = "reported_cases",
  ylab = "Viral copies (µ)",
  title = "Projections for viral signal"
)
```

# Examine WW projections against historic surges

```{r, echo=FALSE, warning=FALSE, message=FALSE}
signal_col <- "rgb(226, 127, 88)"
proj_col <- "rgb(0, 128, 128)"
proj_shade <- "rgba(0, 128, 128, 0.2)"

# Examine ww projections during Mar-Apr 2021 surge
ww_winter_2021_forecast <- short_term_forecast(
    data = ww_clean,
    input = "N1_N2_avg",
    start_date = "2020-12-01",
    end_date = "2021-03-31",
    input_multiplier = 1000000,
    omit_last_date = TRUE,
    generation_time = generation_time,
    incubation_period = incubation_period,
    reporting_delay = reporting_delay,
    output = "both"
)[[1]] %>%
  filter(variable == "reported_cases",
         type == "forecast")

ww_normalized_winter_2021 <- ww_clean %>%
  mutate(N1_N2_avg = N1_N2_avg*1000000) %>%
  full_join(ww_winter_2021_forecast) %>%
  filter(duplicated(date) == FALSE,
         date > first(date),
         !is.na(variable)) %>%
  arrange(date)

ww_proj_call_winter_2021 <- list(type = "avg_data", y_column = "median", name = "Historic projected viral signal", short_name = "projections", color = proj_col, width = 4)

ww_obs_call_winter_2021 <- list(type = "observed_data", y_column = "N1_N2_avg", name = "Observed historic viral signal", short_name = "Daily signal", color = signal_col, opacity = 0.5)

reworked_figure(xaxis = "date", yaxis = list(ww_proj_call_winter_2021, ww_obs_call_winter_2021), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Viral signal", x = "Date", title = "WW projections vs observed signal: Apr 2021"), data = ww_normalized_winter_2021, ticks = FALSE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Examine ww projections during summer 2021
ww_summer_2021_forecast <- short_term_forecast(
    data = ww_clean,
    input = "N1_N2_avg_clean",
    start_date = "2021-06-01",
    end_date = "2021-08-31",
    input_multiplier = 1000000,
    omit_last_date = TRUE,
    generation_time = generation_time,
    incubation_period = incubation_period,
    reporting_delay = reporting_delay,
    output = "both"
)[[1]] %>%
  filter(variable == "reported_cases",
         type == "forecast")

ww_normalized_summer_2021 <- ww_clean %>%
  mutate(N1_N2_avg_clean = N1_N2_avg_clean*1000000) %>%
  full_join(ww_summer_2021_forecast) %>%
  filter(duplicated(date) == FALSE,
         date > first(date),
         !is.na(variable)) %>%
  arrange(date)

ww_proj_call_summer_2021 <- list(type = "avg_data", y_column = "median", name = "Historic projected viral signal", short_name = "projections", color = proj_col, width = 4)

ww_obs_call_summer_2021 <- list(type = "observed_data", y_column = "N1_N2_avg_clean", name = "Observed historic viral signal", short_name = "Daily signal", color = signal_col, opacity = 0.5)

reworked_figure(xaxis = "date", yaxis = list(ww_proj_call_summer_2021, ww_obs_call_summer_2021), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Viral signal", x = "Date", title = "WW projections vs observed signal: Sept 2021"), data = ww_normalized_summer_2021, ticks = FALSE)
```