baseURL = "https://613covid.ca"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Ottawa COVID19"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "./docs"

[languages]
  [languages.en]
    contentDir = "./content/en"
    languageName = "English"
    weight = 1
  [languages.fr]
    contentDir = "./content/fr"
    languageName = "French"
    weight = 2


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "wastewater"
    url = "/wastewater/"
    weight = 3

[[menu.main]]
    name = "model"
    url = "/model/"
    weight = 4

[[menu.main]]
    name = "ww_surv"
    url = "/model/#wastewater"
    parent = "model"
    weight = 2
    
[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 5

[[menu.main]]
    name = "changelog"
    url = "/change-log/"
    weight = 6

[params]
    description = "Ottawa COVID-19 hospital projections."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"
