---
title: "Ottawa COVID Projections"
date: '2020-03-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=FALSE}
ott_data <- read.csv(file.path(getwd(), "Data/Ottawa_hospitalization_estimates_COVID.csv"))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
trace1 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospitalized_50"
    )), 
  mode = "lines", 
  name = "50% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:6:949fbc", 
  x = ott_data$date, 
  ysrc = "wyusuf:6:6cd707", 
  y = ott_data$hospitalized_50, 
  yaxis = "y"
)
trace2 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospitalized_60"
    )), 
  mode = "lines", 
  name = "60% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:6:949fbc", 
  x = ott_data$date, 
  ysrc = "wyusuf:6:3f2245", 
  y = ott_data$hospitalized_60, 
  stackgroup = NULL
)
trace3 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospitalized_70"
    )), 
  mode = "lines", 
  name = "70% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:6:949fbc", 
  x = ott_data$date, 
  ysrc = "wyusuf:6:2a5c46", 
  y = ott_data$hospitalized_70, 
  stackgroup = NULL
)
trace4 <- list(
  meta = list(columnNames = list(
      x = "date", 
      y = "observed_data"
    )), 
  mode = "markers+lines", 
  name = "Observed data", 
  type = "scatter", 
  xsrc = "wyusuf:6:949fbc", 
  x = ott_data$date, 
  ysrc = "wyusuf:6:eea478", 
  y = ott_data$observed_hospitalized
)
trace5 <- list(
  line = list(
    dash = "dash", 
    color = "rgb(24, 24, 24)"
  ), 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospital_capacity"
    )), 
  mode = "lines", 
  name = "Hospital capacity", 
  type = "scatter", 
  xsrc = "wyusuf:6:949fbc", 
  x = ott_data$date, 
  ysrc = "wyusuf:6:90f1b6", 
  y = ott_data$capacity_hospitalized
)
data <- list(trace1, trace2, trace3, trace4, trace5)
layout <- list(
  title = list(text = "Projected census of COVID-19 hospitalizations in Ottawa"), 
  xaxis = list(
    side = "bottom", 
    type = "date", 
    range = c("2020-03-04 12:49:13.9564", "2020-10-16"), 
    title = list(text = "Date"), 
    anchor = "y", 
    domain = c(0, 1), 
    autorange = TRUE
  ), 
  yaxis = list(
    side = "left", 
    type = "linear", 
    range = c(-290.8157396897466, 3595.3060915626183), 
    title = list(text = "Census"), 
    domain = c(0, 1), 
    autorange = TRUE
  ), 
  autosize = TRUE
)
p <- plot_ly()
p <- add_trace(p, fill=trace1$fill, meta=trace1$meta, mode=trace1$mode, name=trace1$name, type=trace1$type, xsrc=trace1$xsrc, x=trace1$x, ysrc=trace1$ysrc, y=trace1$y, yaxis=trace1$yaxis)
p <- add_trace(p, fill=trace2$fill, meta=trace2$meta, mode=trace2$mode, name=trace2$name, type=trace2$type, xsrc=trace2$xsrc, x=trace2$x, ysrc=trace2$ysrc, y=trace2$y, stackgroup=trace2$stackgroup)
p <- add_trace(p, fill=trace3$fill, meta=trace3$meta, mode=trace3$mode, name=trace3$name, type=trace3$type, xsrc=trace3$xsrc, x=trace3$x, ysrc=trace3$ysrc, y=trace3$y, stackgroup=trace3$stackgroup)
p <- add_trace(p, meta=trace4$meta, mode=trace4$mode, name=trace4$name, type=trace4$type, xsrc=trace4$xsrc, x=trace4$x, ysrc=trace4$ysrc, y=trace4$y)
p <- add_trace(p, line=trace5$line, meta=trace5$meta, mode=trace5$mode, name=trace5$name, type=trace5$type, xsrc=trace5$xsrc, x=trace5$x, ysrc=trace5$ysrc, y=trace5$y)
p <- layout(p, title=layout$title, xaxis=layout$xaxis, yaxis=layout$yaxis, autosize=FALSE, width = 1000, height = 500)
p
```



```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
trace1 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "icu_50"
    )), 
  mode = "lines", 
  name = "50% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:10:cbbd3e", 
  x = ott_data$date, 
  ysrc = "wyusuf:10:91b482", 
  y = ott_data$icu_50
)
trace2 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "icu_60"
    )), 
  mode = "lines", 
  name = "60% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:10:cbbd3e", 
  x = ott_data$date, 
  ysrc = "wyusuf:10:f77e77", 
  y = ott_data$icu_60, 
  stackgroup = NULL
)
trace3 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "icu_70"
    )), 
  mode = "lines", 
  name = "70% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:10:cbbd3e", 
  x = ott_data$date, 
  ysrc = "wyusuf:10:9b2b95", 
  y = ott_data$icu_70, 
  stackgroup = NULL
)
trace4 <- list(
  meta = list(columnNames = list(
      x = "date", 
      y = "observed_data"
    )), 
  mode = "markers+lines", 
  name = "Observed data", 
  type = "scatter", 
  xsrc = "wyusuf:10:cbbd3e", 
  x = ott_data$date, 
  ysrc = "wyusuf:10:f2db33", 
  y = ott_data$observed_icu
)
trace5 <- list(
  line = list(
    dash = "dash", 
    color = "rgb(24, 24, 24)"
  ), 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospital_capacity"
    )), 
  mode = "lines", 
  name = "Hospital Capacity", 
  type = "scatter", 
  xsrc = "wyusuf:10:cbbd3e", 
  x = ott_data$date, 
  ysrc = "wyusuf:10:9f6bf8", 
  y = ott_data$capacity_icu
)
data <- list(trace1, trace2, trace3, trace4, trace5)
layout <- list(
  title = list(text = "Projected census of COVID-19 ICU usage in Ottawa"), 
  xaxis = list(
    type = "date", 
    range = c("2020-03-05 14:13:30.5106", "2020-10-16"), 
    title = list(text = "Date"), 
    autorange = TRUE
  ), 
  yaxis = list(
    type = "linear", 
    range = c(-176.97699707235466, 2110.3672103722292), 
    title = list(text = "Census"), 
    autorange = TRUE
  ), 
  autosize = TRUE
)
p <- plot_ly()
p <- add_trace(p, fill=trace1$fill, meta=trace1$meta, mode=trace1$mode, name=trace1$name, type=trace1$type, xsrc=trace1$xsrc, x=trace1$x, ysrc=trace1$ysrc, y=trace1$y)
p <- add_trace(p, fill=trace2$fill, meta=trace2$meta, mode=trace2$mode, name=trace2$name, type=trace2$type, xsrc=trace2$xsrc, x=trace2$x, ysrc=trace2$ysrc, y=trace2$y, stackgroup=trace2$stackgroup)
p <- add_trace(p, fill=trace3$fill, meta=trace3$meta, mode=trace3$mode, name=trace3$name, type=trace3$type, xsrc=trace3$xsrc, x=trace3$x, ysrc=trace3$ysrc, y=trace3$y, stackgroup=trace3$stackgroup)
p <- add_trace(p, meta=trace4$meta, mode=trace4$mode, name=trace4$name, type=trace4$type, xsrc=trace4$xsrc, x=trace4$x, ysrc=trace4$ysrc, y=trace4$y)
p <- add_trace(p, line=trace5$line, meta=trace5$meta, mode=trace5$mode, name=trace5$name, type=trace5$type, xsrc=trace5$xsrc, x=trace5$x, ysrc=trace5$ysrc, y=trace5$y)
p <- layout(p, title=layout$title, xaxis=layout$xaxis, yaxis=layout$yaxis, autosize=FALSE, width = 1000, height = 500)
p
```



```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
trace1 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "ventilation_50"
    )), 
  mode = "lines", 
  name = "50% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:1:9c770a", 
  x = ott_data$date, 
  ysrc = "wyusuf:1:d75a98", 
  y = ott_data$ventilated_50
)
trace2 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "ventilation_60"
    )), 
  mode = "lines", 
  name = "60% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:1:9c770a", 
  x = ott_data$date, 
  ysrc = "wyusuf:1:768815", 
  y = ott_data$ventilated_60, 
  stackgroup = NULL
)
trace3 <- list(
  fill = "tozeroy", 
  meta = list(columnNames = list(
      x = "date", 
      y = "ventilation_70"
    )), 
  mode = "lines", 
  name = "70% social distancing", 
  type = "scatter", 
  xsrc = "wyusuf:1:9c770a", 
  x = ott_data$date, 
  ysrc = "wyusuf:1:3dc4e1", 
  y = ott_data$ventilated_70, 
  stackgroup = NULL
)
trace4 <- list(
  meta = list(columnNames = list(
      x = "date", 
      y = "observed_data"
    )), 
  mode = "markers+lines", 
  name = "Observed data", 
  type = "scatter", 
  xsrc = "wyusuf:1:9c770a", 
  x = ott_data$date, 
  ysrc = "wyusuf:1:420b6f", 
  y = ott_data$observed_ventilated
)
trace5 <- list(
  line = list(
    dash = "dash", 
    color = "rgb(24, 24, 24)"
  ), 
  meta = list(columnNames = list(
      x = "date", 
      y = "hospital_capacity"
    )), 
  mode = "lines", 
  name = "Hospital capacity", 
  type = "scatter", 
  xsrc = "wyusuf:1:9c770a", 
  x = ott_data$date, 
  ysrc = "wyusuf:1:a5d486", 
  y = ott_data$capacity_ventilated
)
data <- list(trace1, trace2, trace3, trace4, trace5)
layout <- list(
  title = list(text = "Projected census of COVID-19 ventilation usage in Ottawa"), 
  xaxis = list(
    type = "date", 
    range = c("2020-03-05 14:13:30.5106", "2020-10-16"), 
    title = list(text = "Date"), 
    autorange = TRUE
  ), 
  yaxis = list(
    type = "linear", 
    range = c(0, 688.421052631579), 
    title = list(text = "Census"), 
    autorange = TRUE
  ), 
  autosize = TRUE
)
p <- plot_ly()
p <- add_trace(p, fill=trace1$fill, meta=trace1$meta, mode=trace1$mode, name=trace1$name, type=trace1$type, xsrc=trace1$xsrc, x=trace1$x, ysrc=trace1$ysrc, y=trace1$y)
p <- add_trace(p, fill=trace2$fill, meta=trace2$meta, mode=trace2$mode, name=trace2$name, type=trace2$type, xsrc=trace2$xsrc, x=trace2$x, ysrc=trace2$ysrc, y=trace2$y, stackgroup=trace2$stackgroup)
p <- add_trace(p, fill=trace3$fill, meta=trace3$meta, mode=trace3$mode, name=trace3$name, type=trace3$type, xsrc=trace3$xsrc, x=trace3$x, ysrc=trace3$ysrc, y=trace3$y, stackgroup=trace3$stackgroup)
p <- add_trace(p, meta=trace4$meta, mode=trace4$mode, name=trace4$name, type=trace4$type, xsrc=trace4$xsrc, x=trace4$x, ysrc=trace4$ysrc, y=trace4$y)
p <- add_trace(p, line=trace5$line, meta=trace5$meta, mode=trace5$mode, name=trace5$name, type=trace5$type, xsrc=trace5$xsrc, x=trace5$x, ysrc=trace5$ysrc, y=trace5$y)
p <- layout(p, title=layout$title, xaxis=layout$xaxis, yaxis=layout$yaxis, autosize=FALSE, width = 1000, height = 500)
p
```