---
title: "WW testing"
author: "Warsame Yusuf"
date: "25/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load}
# load library, packages, functions
library(EpiNow2)
library(tidyverse)
library(lubridate)
source("R/epinow_functions.R")
source("R/wastewater.R")

# load WW data
ott_observed_waste <- read.csv("https://raw.githubusercontent.com/Big-Life-Lab/covid-19-wastewater/main/data/wastewater_virus.csv")

# Clean WW data for Epinow2
ww_clean <- wastewater_prep(ott_observed_waste) %>%
  epinow_data_prep(start_date = "2020-04-08", parameter = "N1_N2_avg") # parameter can be modified for N1 or N2

# Set reporting delay, generation time, incubation period
reporting_delay <- bootstrapped_dist_fit(rlnorm(100, log(4), 1), max_value = 30)
generation_time <-
  get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
incubation_period <-
  get_incubation_period(disease = "SARS-CoV-2", source = "lauer")
```

```{r}
# execute epinow2 sim
ww_short_forecast <- short_term_forecast(
  data = ww_clean,
  generation_time = generation_time,
  incubation_period = incubation_period,
  reporting_delay = reporting_delay,
  output = "both"
)
```

```{r}
# Visualize projections
ww_projections <- ww_short_forecast[[1]]

short_term_plot(
  projections = ww_projections,
  obs_data = ott_covid_data,
  forecast_type = "infections",
  ylab = "New cases",
  title = "Projections for new cases by episode date"
)

short_term_plot(
  projections = ww_projections,
  obs_data = ott_covid_data,
  forecast_type = "reported_cases",
  ylab = "New cases",
  title = "Projections for new cases by reported date"
)

short_term_plot(
  projections = ww_projections,
  obs_data = ott_covid_data,
  forecast_type = "R",
  ylab = "R",
  title = "Rt projections"
)
```