---
title: Changelog
---

**Updates involving only data updates will no longer be documented.**

# V2.0.0
2020-05-07

- Replaced Ottawa hospital census data with The Ottawa Hospital (TOH) census
data to 2020-05-05.
- Projections are now done using the Bayseian SEIR
[extension](https://github.com/pennsignals/chime_sims) of the CHIME model.
  - Model uses existing TOH census data to generate simulated projections for
  hospitalizations and ventilator usage.
  - Model parameters updated and can be viewed [here](/model#parameters).
- Projections made based on current effective physical distancing and 20%
reduction in physical distancing from current measures with confidence
intervals.
- ICU and death projections removed.

# V1.5.2
2020-04-27

- Updated Ottawa hospital census data to 2020-04-26.
- Changes to model parameters:
  - Initial doubling time set to 4 days.
  - Physical distancing implementation set to 50-70% (Current effective physical
  distancing set to 58%).
- Current effective physical distancing value added to projection legends.
- Note added regarding observed deaths in Ottawa.

# V1.5.1
2020-04-23

- Updated Ottawa hospital census data to 2020-04-22.
- Updated parameters based on observed hospitalization at the Ottawa Hospital
from April 8 to 18. This time period was chosen because it represented a period
of steady state when admissions equaled discharges. Estimates based on the
proportion of hospital census in ICU or ventilated.
  - ICU % changed from 0.75 to 0.96 (based on 37% of observed hospitalizations).
  - Ventilated % changed from 0.5 to 0.73 (based on 28% of observed
  hospitalizations).
  - ICU length of stay changed from 16 to 10 days.

# V1.5.0
2020-04-20

- Updated Ottawa hospital census data to 2020-04-19.
- New dashboard providing current hospitalization data updated daily.
- Minor changes to model parameters:
  - Current effective physical distancing set to 63%. Projections made for
  50%, current, and 70% physical distancing.
  - Date of physical distancing implementation set to 2020-04-20.

# V1.4.1
2020-04-17

- Updated Ottawa hospital census data to 2020-04-16.
- Minor changes to model parameters:
  - Current # of hospitalized patients changed from 43 to 37.
  - Date of physical distancing implementation set to 2020-04-17.

# V1.4.0
2020-04-16

- Updated Ottawa hospital census data to 2020-04-15.
- Changes to model parameters:
  - Doubling time changed from 5 days to 31.98 days based on observed doubling
  time in the last week.
  - Changed physical distancing % from 50-70 to 0-20. Based on current observed
  doubling time, effective physical distancing is currently at 50%; and
  obtaining 60% or 70% physical distancing means an increase in physical
  distancing by 10% or 20% respectively.
  - Infectious days changed from 10 days to 7 days.
- Edits to documentation.

# V1.3.0
2020-04-15

- Updated Ottawa hospital census data to 2020-04-14
- New figure: Observed census & doubling time
  - Figure displays observed acute-care and ICU census in Ottawa
  - Figure estimates weekly doubling time based on observed data

# V1.2.1
2020-04-14 (12:30pm)

- Updated Ottawa hospital census data to 2020-04-13
- No change in model parameters.

# V1.2.0
2020-04-14 (9:30am)

- Updated Ottawa hospital census data to 2020-04-12
- Changes to model parameters:
  - Doubling time changed from 4 days to 5 days
  - Date of physical distancing implementation set to 2020-04-12
  - Infectious days changed from 14 days to 10 days
- Edits to documentation

# V1.1.4
2020-04-11

- Updated Ottawa hospital census data to 2020-04-10
- COVID-19 icon added to navbar. 
- No change in model parameters.

# V1.1.3
2020-04-10

- Updated Ottawa hospital census data to 2020-04-09
- No change in model parameters.
- Improvements to figures.

# V1.1.2
2020-04-09

- Updated Ottawa hospital census data to 2020-04-08
- Used doubling time of 4 days as opposed to first hospitalization date to
generate projections
- Improvements to documentation, including additional figures

# V1.1.1
2020-04-08

- Improvements to mobile version of website

# V1.1.0
2020-04-08

- Projections added:
  - Peak hospitalizations
- Updates to documentation

# V1.0.0
2020-04-07

- Website now public
- Updated Ottawa hospital census data to 2020-04-06

# V0.3.0
2020-04-06

- Updated Ottawa hospital census data to 2020-04-04
- Projections added:
    - Census and daily acute care hospitalizations
- Expanded description of documentation

# V0.2.0
2020-04-03

- Updated Ottawa hospital census data to 2020-04-02.
- Projections added:
    - Daily admissions.
    - Daily and total deaths in hospital (provisional).
- Overview updated.
- Improvements to the labels and figures.

Changes to key parameters:

- Census (acute and ICU) = 24 patients. Ottawa hospital census data to 2020-04-03.
- Hospital bed doubling time = 4 days.
- Model rojections are based on the CHIME model v1.1.2

# V0.1.0 
2020-04-01

Initial projections based on Ottawa hospital census data to 2020-03-29.

Key parameters:

- Census (acute and ICU) = 21 patients
- Hospital bed doubling time = 4 days
- Model Projections are based on the [CHIME model](https://penn-chime.phl.io/) v1.1.0

# Roadmap

The main purpose of this site is to visualize Ottawa-based projections for models performed by other teams.

- Review and update model parameters based on recent published studies. Priories for review:
    - ventilated patients
    - deaths
- Add plot for observed hospital census trend, with estimated doubling time. 




