---
title: "epinow-hosp-ww-assessment"
author: "Warsame Yusuf"
date: "15/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load}
# load library, packages, functions
library(EpiNow2)
library(tidyverse)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stats)
library(zoo)
library(stringr)
library(RColorBrewer)

source("../R/epinow_functions.R")
source("../R/open_ottawa_scripts.R")
source("../R/wastewater.R")

# load covid & ww data
ott_covid_data <-
  read.csv(file.path(getwd(), "../Data/Observed Data/OPH_Observed_COVID_Data.csv"))

ott_observed_waste <- read.csv("https://raw.githubusercontent.com/Big-Life-Lab/covid-19-wastewater/main/data/wastewater_virus.csv")
waste_clean <- wastewater_prep(ott_observed_waste)
#ott_covid_waste <- merge_data(ott_covid_data, waste_clean)

# Set reporting delay, generation time, incubation period
reporting_delay <- bootstrapped_dist_fit(rlnorm(100, log(4), 1), max_value = 30)
generation_time <-
  get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
incubation_period <-
  get_incubation_period(disease = "SARS-CoV-2", source = "lauer")
```

## Short term hospitalizations
```{r}
# set number of cores to use fitting the model
# no benefit on runtime if cores > chains which is set to 4 by default
options(mc.cores = 4)
```

```{r}
# Prep existing data
hosp_data <- ott_covid_data %>%
  select(date, observed_new_cases, observed_census_ICU_p_acute_care) %>%
  mutate(date = as.Date(date)) %>%
  rename(primary = "observed_new_cases", secondary = "observed_census_ICU_p_acute_care") %>%
  filter(date >= (max(as.Date(date)) - 12*7))

hosp_data <- data.table::setDT(hosp_data)
```

```{r}

# Estimate relationship between cases and hospitalization
cases_to_hosp <- estimate_secondary(hosp_data, 
                                    delays = delay_opts(list(mean = 2.5, mean_sd = 0.2, 
                                                               sd = 0.47, sd_sd = 0.1, max = 21)),
                                    secondary = secondary_opts(type = "prevalence"),
                                    obs = obs_opts(scale = list(mean = 0.01, sd = 0.0025)),
                                    control = list(adapt_delta = 0.95))
```

```{r}
# Forecast hospitalizations using case data
case_forecast <- epinow(reported_cases = copy(hosp_data)[, .(date, confirm = primary)], 
                        generation_time = generation_time,
                        delays = delay_opts(incubation_period, reporting_delay),
                        rt = rt_opts(prior = list(mean = 1.5, sd = 0.5), rw = 7),
                        gp = NULL, horizon = 21)

hosp_forecast <- forecast_secondary(cases_to_hosp, case_forecast$estimates)

# Prep data to be visualized
hosp_proj <- hosp_forecast[[2]]

hosp_proj$variable <- "reported_cases"

hosp_proj$type <- ifelse(hosp_proj$date <= max(ott_covid_data$date), "estimate", "forecast")

# Plot forecasted data
plot <- short_term_plot(projections = hosp_proj, obs_data = ott_covid_data, obs_column = "observed_census_ICU_p_acute_care", forecast_type = "reported_cases", ylab = "Hospital census", title = "Hospital census projections")

plot
```

## Assessing performance of projections on previous data

```{r}
hist_proj <- list()
# Filter for data beyond Sept 1
ott_covid_data <- ott_covid_data %>%
  mutate(date = as.Date(date)) %>%
  filter(date >= as.Date("2020-09-01"))

time_frame <- c(0, 21, 42, 63, 84, 105)
x <- 0

for(i in time_frame){
  x <- x + 1
  hosp_i <- ott_covid_data %>%
  select(date, observed_new_cases, observed_census_ICU_p_acute_care) %>%
  mutate(date = as.Date(date)) %>%
  rename(primary = "observed_new_cases", secondary = "observed_census_ICU_p_acute_care") %>%
  filter(date >= (first(as.Date(ott_covid_data$date)) + i) &
           date <= (first(as.Date(ott_covid_data$date)) + i + 90))
  
  hosp_i <- data.table::setDT(hosp_i)
  
  cases_to_hosp_i <- estimate_secondary(hosp_i, 
                                    delays = delay_opts(list(mean = 2.5, mean_sd = 0.2, 
                                                               sd = 0.47, sd_sd = 0.1, max = 21)),
                                    secondary = secondary_opts(type = "prevalence"),
                                    obs = obs_opts(scale = list(mean = 0.01, sd = 0.0025)),
                                    control = list(adapt_delta = 0.95))
  
  case_forecast_i <- epinow(reported_cases = copy(hosp_i)[, .(date, confirm = primary)], 
                        generation_time = generation_time,
                        delays = delay_opts(incubation_period, reporting_delay),
                        rt = rt_opts(prior = list(mean = 1.5, sd = 0.5), rw = 7),
                        gp = NULL, horizon = 21)
  
  hosp_forecast_i <- forecast_secondary(cases_to_hosp_i, case_forecast_i$estimates)
  
  # Prep data to be visualized
  hosp_proj_i <- hosp_forecast_i[[2]]
  
  hosp_proj_i$variable <- "reported_cases"
  
  hosp_proj_i$type <- ifelse(hosp_proj_i$date <= max(hosp_i$date), "estimate", "forecast")
  
  hist_proj[[x]] <- hosp_proj_i
}

save(hist_proj, file = "hist_proj.RData")
```

```{r}
# Load hist_proj .RData
load("hist_proj.RData")
hist_projections <- bind_rows(hist_proj)
```

## Wastewater
```{r}
## Prep data
case_data <- ott_covid_data %>%
  select(date, observed_new_cases) %>%
  mutate(date = as.Date(date))

ww_data <- waste_clean %>%
  select(date, N1_N2_avg) %>%
  mutate(date = as.Date(date)) %>%
  left_join(case_data, by = "date") %>%
  rename(primary = "observed_new_cases", secondary = "N1_N2_avg") %>%
  relocate(secondary, .after = primary) %>%
  mutate(secondary = secondary *1000000) %>%
  na.omit %>%
  mutate(secondary = as.integer(secondary)) %>%
  filter(date >= (max(as.Date(date)) - 12*7))

ww_data <- data.table::setDT(ww_data)
```

```{r}
# Estimate relationship between cases and ww
cases_to_ww <- estimate_secondary(ww_data, 
                                  delays = delay_opts(list(mean = -5, mean_sd = 0.2, 
                                                           sd = 0.47, sd_sd = 0.1, max = 0)),
                                  secondary = secondary_opts(type = "prevalence"),
                                  obs = obs_opts(scale = list(mean = 0.01, sd = 0.0025)),
                                  control = list(adapt_delta = 0.95))
```

```{r}
# Forecast hospitalizations using case data
case_forecast <- epinow(reported_cases = copy(ww_data)[, .(date, confirm = primary)], 
                      generation_time = generation_time,
                      delays = delay_opts(incubation_period, reporting_delay),
                      rt = rt_opts(prior = list(mean = 1.5, sd = 0.5), rw = 7),
                      gp = NULL, horizon = 14)

ww_forecast <- forecast_secondary(cases_to_ww, case_forecast$estimates, all_dates = TRUE)
```

```{r}
# Prep data to be visualized
ww_proj <- ww_forecast[[2]]

ww_proj$variable <- "reported_cases"

ww_proj$type <- ifelse(ww_proj$date <= max(ott_covid_data$date), "estimate", "forecast")

# Plot forecasted data
plot <- short_term_plot(projections = ww_proj, obs_data = ww_data, obs_column = "secondary", forecast_type = "reported_cases", ylab = "Wastewater signal (µ)", title = "Wastewater signal projections")

plot
```