---
title: "EpiNow2 tutorial"
author: "Warsame Yusuf"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Load the necessary packages
library(tidyverse)
library(ggplot2)
library(EpiNow2)
library(stringr)
library(purrr)
library(lubridate)
library(plotly)
library(RColorBrewer)
library(zoo)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Source the necessary R files containing the functions of interest
source("../R/epinow_functions.R")
source("../R/wastewater.R")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Load case/hospitalizations dataset
ott_covid_data <- read.csv(file.path(getwd(), "../Data/Observed data/OPH_Observed_COVID_Data.csv"))

# Load wastewater dataset
ww_data <- read.csv("https://raw.githubusercontent.com/Big-Life-Lab/PHESD/main/Wastewater/Ottawa/Data/wastewater_virus.csv")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Prepare WW data for projections
ww_clean <- wastewater_prep(ww_data) %>% # function cleans and organizes WW data
  select(date, N1_N2_avg_clean) %>% # select columns from cleaned dataset
  mutate(date = as.Date(date)) # ensure date column is in date class
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Set reporting delay, generation time, incubation period
reporting_delay <- bootstrapped_dist_fit(rlnorm(100, log(4), 1), max_value = 30)
generation_time <-
  get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
incubation_period <-
  get_incubation_period(disease = "SARS-CoV-2", source = "lauer")

# Running short term projections
ott_short_forecast <- short_term_forecast(
  data = ott_covid_data, # data to run projections from
  parameter = "observed_new_cases", # column to feed data into
  start_date = "2021-12-01", # can be changed
  parameter_weight = 1, # multiplier for data that <0 (e.g. ww signal)
 # end_date = "2020-11-24", # can be changed, if missing will default to last day
  omit_last_date = TRUE,
  generation_time = generation_time, # estimated time between two generations of virus
  incubation_period = incubation_period, # time between exposure and symptom onset
  reporting_delay = reporting_delay, # time between exposure and reported 
  output = "projections" # output type
)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Visualizing projections
short_term_plot(
  projections = ott_short_forecast, # projection data
  obs_data = ott_covid_data, # observed data
  obs_column = "observed_new_cases", # observed data column
  forecast_type = "reported_cases", # forecast type
  ylab = "New cases", # yaxis label
  title = "Projections for new cases" # plot title
)
```