---
title: "Ottawa COVID-19 Projections"
params: 
  lang: "en"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
lang <- params$lang
```

```{r include=FALSE}
##Load localization file
source("../../R/localization.R")
localization_data <- read.csv(file.path(getwd(),"../../Data/Covid Localization - Home Page.csv"))
```

```{r, results='hold', echo=FALSE, comment=NA}
time <- .POSIXct(Sys.time(), "America/New_York")
intro<- insert_translation(localization_data, lang, "Intro", c(format(time, '%d %B, %Y, %X')))
dt_label_half <- insert_translation(localization_data, lang, "DT_label_half")
dt_label_double <- insert_translation(localization_data, lang, "DT_label_double")
dt_label_no_change <- insert_translation(localization_data, lang, "DT_label_no_change")
more <- insert_translation(localization_data, lang, "more")
fewer <- insert_translation(localization_data, lang, "fewer")
the_same <- insert_translation(localization_data, lang, "the_same")
```
`r intro`

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# libraries
library(plotly)
library(tidyverse)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stats)
library(covidseir)
library(zoo)
library(EpiNow2)
library(stringr)
library(purrr)
library(RColorBrewer)

# scripts
source("../../R/lag_replacement.R")
source("../../R/observed_data.R")
source("../../R/data_conversion.R")
source("../../R/hosp_projections.R")
source("../../R/open_ottawa_scripts.R")
source("../../R/plot_case_projections.R")
source("../../R/chime_functions.R")
source("../../R/epinow_functions.R")

# data
ott_observed <- read.csv(file.path(getwd(), "../../Data/Observed data/OPH_Observed_COVID_Data.csv"))
load("../../Data/short_term_forecast.RData")
ott_projections <- ott_short_forecast[[1]]

## Observed census
exp_census <- calc_expected_values_for_n_weeks(data = ott_observed, number_weeks = 3, first_day = 1)

## Dt = doubling (or halving) time
Dt_census <- exp_census[[2]][[3]]

diff_census <- (last(na.omit(exp_census[[3]][[3]][[1]])) -
           first(na.omit(exp_census[[3]][[3]][[1]])))/first(na.omit(exp_census[[3]][[3]][[1]]))

if(abs(diff_census) <= 0.05){
  Dt_census <- 0
}

if(Dt_census == Inf) {
  Dt_census <- 0
}

Dt_label_census = switch( 
  (sign(Dt_census) + 2),
  dt_label_half,
  dt_label_no_change,
  dt_label_double)

more_less_census = switch(
  (sign(Dt_census) + 2),
  fewer,
  the_same,
  more
)

dt <- ott_short_forecast[[2]][[5]][[1]]
dt_label = switch( 
  (sign(dt) + 2),
  "Case halving time:",
  "No change:",
  "Case doubling time:")

## Observed new cases by episode date (excluding past 7 days)
ott_observed_episodes <- as.data.frame(ott_observed[1:(nrow(ott_observed) - 6),])

exp_new_episodes <- calc_expected_values_for_n_weeks(data = ott_observed_episodes,
                                                     number_weeks = 3,
                                                     observed_columns_name = "observed_new_episodes",
                                                     first_day = 1)

diff_new_episodes <- (last(na.omit(exp_new_episodes[[3]][[3]][[1]])) -
           first(na.omit(exp_new_episodes[[3]][[3]][[1]])))/first(na.omit(exp_new_episodes[[3]][[3]][[1]]))

if(abs(diff_new_episodes) <= 0.05){
  Dt_new_episodes <- 0
}

## Dt = doubling (or halving) time
Dt_new_episodes <- exp_new_episodes[[2]][[3]]

if(Dt_new_episodes == Inf) {
  Dt_active_cases <- 0
}

Dt_label_new_episodes = switch( 
  (sign(Dt_new_episodes) + 2),
  dt_label_half,
  dt_label_no_change,
  dt_label_double)

more_less_new_episodes = switch(
  (sign(Dt_new_episodes) + 2),
  fewer,
  the_same,
  more
)


## Observed active cases
exp_active_cases <- calc_expected_values_for_n_weeks(data = ott_observed,
                                                     number_weeks = 3,
                                                     observed_columns_name = "observed_active_cases",
                                                     first_day = 1)

diff_active_cases <- (last(na.omit(exp_active_cases[[3]][[3]][[1]])) -
           first(na.omit(exp_active_cases[[3]][[3]][[1]])))/first(na.omit(exp_active_cases[[3]][[3]][[1]]))

if(abs(diff_active_cases) <= 0.05){
  Dt_active_cases <- 0
}

## Dt = doubling (or halving) time
Dt_active_cases <- exp_active_cases[[2]][[3]]

if(Dt_active_cases == Inf) {
  Dt_active_cases <- 0
}

Dt_label_active_cases = switch( 
  (sign(Dt_active_cases) + 2),
  dt_label_half,
  dt_label_no_change,
  dt_label_double)

more_less_active_cases = switch(
  (sign(Dt_active_cases) + 2),
  fewer,
  the_same,
  more
)


# Colors
acute_col <- "rgb(72, 137, 194)"
acute_shade <- "rgba(72, 137, 194, 0.3)"
acute_hex <- "#488AC2"

vent_col <- "rgb(23, 63, 95)"
vent_shade <- "rgba(23, 63, 95, 0.3)"

icu_col <- "rgb(60, 174, 163)"
icu_shade <- "rgba(60, 174, 163)"

current_case_col <- "rgb(0, 128, 128)"
current_case_shade <- "rgba(0, 128, 128)"
current_case_hex <- "#008080"

increase_col <- "rgb(246, 213, 86)"
increase_shade <- "rgba(246, 213, 86)"
increase_hex <- "#F6D556"

reduction_col <- "rgb(133, 194, 43)"
reduction_shade <- "rgba(133, 194, 43)"
reduction_hex <- "#85c22b"
```

```{r, results='hold', echo=FALSE, comment=NA}
line_break <- insert_translation(localization_data, lang, "break")
dashboard <- insert_translation(localization_data, lang, "Dashboard",
                                c(as.character(tail(ott_observed$date, n=1)),
                                  dt_label,
                                  dt,
                                  #last(na.omit(ott_observed$observed_active_cases)),
                                  last(na.omit(ott_observed$observed_census_ICU_p_acute_care)),
                                  last(na.omit(ott_observed$observed_census_acute_care)),
                                  last(na.omit(ott_observed$observed_census_ICU))))

definitions <- insert_translation(localization_data, lang, "Definitions")

short_range_forecast <- insert_translation(localization_data, lang, "ShortRangeForecast", 
                                           c(more_less_active_cases,
                                             Dt_label_active_cases,
                                             round(abs(exp_active_cases[[2]][[3]]), 0),
                                             round(100*exp_active_cases[[4]][[3]], 0),
                                             more_less_new_episodes,
                                             Dt_label_new_episodes,
                                             round(abs(exp_new_episodes[[2]][[3]]), 0),
                                             round(100*exp_new_episodes[[4]][[3]], 0),
                                             more_less_census,
                                             Dt_label_census,
                                             round(abs(exp_census[[2]][[3]]), 0),
                                             round(100*exp_census[[4]][[3]], 0)))

defintions <- insert_translation(localization_data, lang, "Definitions")

past_data_title <- insert_translation(localization_data, lang, "PastData_title") 

past_hospital_text <- insert_translation(localization_data, lang, "PastHospital_text",
                                         c(Dt_label,
                                           round(abs(exp_census[[2]][[3]]), 0),
                                           round(effective_pd, 0))) 

observed_cases <- insert_translation(localization_data, lang, "observed_cases")

observed_cases_text <- insert_translation(localization_data, lang, "observed_cases_text")

observed_admits <- insert_translation(localization_data, lang, "observed_admits")

projected_hospital_title <- insert_translation(localization_data, lang, "ProjectedHospital_title")

case_projections <- insert_translation(localization_data, lang, "case_projections")

case_projections_text <- insert_translation(localization_data, lang, "case_projections_text",
                                            c(max(ott_projections$date, na.rm = TRUE)))

hosp_projections <- insert_translation(localization_data, lang, "hosp_projections")
```

`r dashboard`

`r past_data_title`

`r observed_cases`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Visualize current daily cases
observed_new_episodes <- list(type = "observed_data", y_column = "observed_new_episodes", name = "New cases by episode date", color = current_case_hex)

reworked_figure(
    xaxis = "date",
    yaxis = list(observed_new_episodes),
    titles = c(y = "Daily cases", x = "Date", title = "Observed daily COVID-19 cases in Ottawa by episode date"),
    data = ott_observed
  )
```

`r observed_cases_text`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Ottawa Hospital data section @Warsame
exp_census[[1]]$DT1 <- exp_census[[3]][[1]]$expected_val
exp_census[[1]]$DT2 <- exp_census[[3]][[2]]$expected_val
exp_census[[1]]$DT3 <- exp_census[[3]][[3]]$expected_val

# Graph selection list
icu_call <- list(type = "observed_data", y_column = "observed_census_ICU", name = "ICU census", color = icu_col)
acute_care <- list(type = "observed_data", y_column = "observed_census_acute_care", name = "Acute care census", color = acute_col)

# Plotly creation 
ottawa_hosp <-
  reworked_figure(
    xaxis = "date",
    yaxis = list(icu_call, acute_care), #DT1, DT2, DT3),
    titles = c(y = "# of patients", x = "Date", title = "Observed census of COVID-19 hospitalizations in Ottawa hospitals"),
    data = exp_census[[1]]
  )

# Display graph
ottawa_hosp
```

`r past_hospital_text`

`r line_break`

`r observed_admits`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
observed_daily_ICU_p_acute_care <- list(type = "observed_data", y_column = "observed_new_ICU_p_acute_care", name = "Reported number of patients", color = acute_col)



ICU_p_acute_care <-
  reworked_figure(
    xaxis = "date",
    yaxis = list(observed_daily_ICU_p_acute_care),
    titles = c(y = "# of patients", x = "Date", title = "Observed new COVID-19 hospitalizations in Ottawa"),
    data = ott_observed
  )

ICU_p_acute_care
```

`r line_break`

`r projected_hospital_title`

`r case_projections`

`r case_projections_text`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# visualize epinow forecast

short_term_plot(
  projections = ott_projections,
  obs_data = ott_observed,
  forecast_type = "reported_cases",
  ylab = "New cases",
  title = "Short-term daily COVID-19 cases in Ottawa"
)
```

`r line_break`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Set up SEIR model

## Set up sampling fractions
samp_frac <- c(rep(0.14, 13), rep(0.21, 38))
samp_frac <- c(samp_frac, rep(0.37, nrow(ott_observed_episodes) - length(samp_frac)))

## Set up contact rate breakpoints
f_seg <- c(0, rep(1, nrow(ott_observed_episodes) - 1))
day_new_f <- which(as.character(ott_observed_episodes[["date"]]) == ymd("2020-05-19")) # Date of phase 1 reopening
f_seg[seq(day_new_f, length(f_seg))] <- 2
day_ch <- which(as.character(ott_observed_episodes[["date"]]) == ymd("2020-06-12")) # Date of phase 2 reopening
f_seg[seq(day_ch, length(f_seg))] <- 3

day_ch <- which(as.character(ott_observed_episodes[["date"]]) == ymd("2020-07-17")) # Date of phase 3 reopening
f_seg[seq(day_ch, length(f_seg))] <- 4

day_ch <- which(as.character(ott_observed_episodes[["date"]]) == ymd("2020-10-09")) # Date of modified phase 2
f_seg[seq(day_ch, length(f_seg))] <- 5

day_ch <- which(as.character(ott_observed_episodes[["date"]]) == ymd("2020-11-09")) # End date of modified phase 2
f_seg[seq(day_ch, length(f_seg))] <- 6
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
# Fit SEIR model of observed new cases in Ottawa
fit <- fit_seir(
  daily_cases = ott_observed_episodes[["adjusted_episode_cases"]],
  samp_frac_fixed = samp_frac, 
  f_seg = f_seg,
  i0_prior = c(log(7), 1), # 7 total cases on March 1st, 2020
  e_prior = c(0.85, 0.05), # 85% of residents social distancing
  start_decline_prior = c(log(24), 0.1), # Starting date of closing of non-essential businesses (March 24th, 2020)
  end_decline_prior = c(log(34), 0.1), # 10 day buffer to ramp in social distancing
  f_prior = cbind(c(0.4, 0.5, 0.6, 0.65, 0.6, 0.6), c(0.2, 0.2, 0.2, 0.2, 0.2, 0.2)),
  R0_prior = c(log(2.5), 0.2), # Starting R0 value
  N_pop = 1049486, # Ottawa population
  iter = 500, # number of posterior samples
  fit_type = "optimizing" # for speed only
)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Prepare model fit
proj <- project_seir(fit, iter = 1:50)
tidy_proj <- tidy_seir(proj, resample_y_rep = 20)
first_day <- min(as.Date(ott_observed_episodes[["date"]])) # first observation date
last_day <- 500 # how many days to create dates for
lut <- tibble( # Create look-up table (lut)
  day = seq_len(last_day),
  date = seq(first_day, first_day + length(day) - 1, by = "1 day")
)

tidy_proj <- left_join(tidy_proj, lut, by = "day")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Generate projections for SEIR model fit
ott_case_projections <- proj_generation(fit, lut, ott_observed_episodes, project_to = "2021-03-31", day_start_reduction = 7, pct_change = 10)

# Create data set to visualize projections
projection_data <- case_projection_data(ott_case_projections, 10)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Visualize projections
case_projection_plot(projection_data, ott_observed_episodes, current_col = current_case_hex, reduction_col = reduction_hex, increase_col = increase_hex, value_column = "observed_new_episodes", date_column = "date", title = "Long-term daily COVID-19 cases in Ottawa", pct_change = 10)
```

`r line_break`

`r hosp_projections`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Import projections
ott_projections <- read.csv(file.path(getwd(), "../../Data/OPH_projection_estimates.csv"))
source("../../R/hosp_projections.R")
hosp_fun(ott_projections, "hosp_census", title = "Projected COVID-19 hospital census in Ottawa", y = "Census (Number of patients)", current_color = acute_col, current_shade = acute_shade, reduction_value = 10, reduction_color = reduction_col, reduction_shade = reduction_shade, increase_value = 10, increase_color = increase_col, increase_shade = increase_shade, observed_name = "Observed census of patients", project_to = "2021-03-31")
```

`r line_break`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("../../R/hosp_projections.R")
hosp_fun(ott_projections, "hosp_admits", title = "Projected COVID-19 daily hospital admissions in Ottawa", y = "New admissions (Number of patients)", current_color = acute_col, current_shade = acute_shade, reduction_value = 10, reduction_color = reduction_col, reduction_shade = reduction_shade, increase_value = 10, increase_color = increase_col, increase_shade = increase_shade, observed_name = "Observed # of daily admissions", project_to = "2021-03-31")
```

`r line_break`

`r definitions`
