---
title: "Ottawa COVID-19 Case Projections"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# libraries
library(plotly)
library(tidyverse)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stats)
library(covidseir)

# scripts
source("../../R/lag_replacement.R")
source("../../R/observed_data.R")
source("../../R/data_conversion.R")
source("../../R/hosp_projections.R")
source("../../R/open_ottawa_scripts.R")
source("../../R/plot_case_projections.R")

# Pull JSON objects from OpenOttawa
ottawa_case_data <-
  fromJSON("https://opendata.arcgis.com/datasets/6bfe7832017546e5b30c5cc6a201091b_0/FeatureServer/0/query?where=1%3D1&outFields=Cumulative_Active_Cases_by_Episode_Date,7-day_Average_of_Newly_Reported_cases_by_Reported_Date,Daily_Cases_Linked_to_a_Community_Outbreak_by_Episode_Date,Daily_Cases_Not_Linked_to_an_Outbreak_ie_Sporadic_Cases_by_Episode_Date,Daily_Cases_Linked_to_an_Institutional_Outbreak_by_Episode_Date,Cumulative_Deaths_by_Date_of_Death,_Date,Daily_Cases_by_Reported_Date,Daily_Cases_by_Episode_Date,Cases_Newly_Admitted_to_Hospital,Cases_Currently_in_Hospital,Cases_Currently_in_ICU&outSR=4326&f=json")
ottawa_test_data <-
  fromJSON("https://opendata.arcgis.com/datasets/26c902bf1da44d3d90b099392b544b81_0/FeatureServer/0/query?where=1%3D1&outFields=_Date,Number_of_Tests,Daily_%_Positivity&outSR=4326&f=json")

# data
ott_observed_covid <- data_creation(ottawa_case_data, ottawa_test_data)[["data"]]
ott_observed_covid <- ott_observed_covid[ott_observed_covid$date >= "2020-03-01",] # Date when sustained new cases began
# cut-off last 7 days
ott_observed_covid <- as.data.frame(ott_observed_covid[1:(nrow(ott_observed_covid) - 7),])

# Colors
current_col <- "rgb(72, 137, 194)"
current_shade <- "rgba(72, 137, 194, 0.3)"
current_hex <- "#488AC2"

reduction_col <- "rgb(243, 213, 86)"
reduction_shade <- "rgba(243, 213, 86, 0.3)"
reduction_hex <- "#F6D556"

increase_col <- "rgb(133, 194, 43)"
increase_shade <- "rgba(133, 194, 43)"
increase_hex <- "#85c22b"
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Set up SEIR model
## Set up sampling fractions
samp_frac <- c(rep(0.14, 13), rep(0.21, 38))
samp_frac <- c(samp_frac, rep(0.37, nrow(ott_observed_covid) - length(samp_frac)))

## Set up contact rate breakpoints
f_seg <- c(0, rep(1, nrow(ott_observed_covid) - 1))
day_new_f <- which(ott_observed_covid$date == ymd("2020-05-19")) # Date of phase 1 reopening
f_seg[seq(day_new_f, length(f_seg))] <- 2
day_ch <- which(ott_observed_covid$date == ymd("2020-06-12")) # Date of phase 2 reopening
f_seg[seq(day_ch, length(f_seg))] <- 3
```

## Observed case data

Data to `r as.character(tail(ott_observed_covid$date, n=1))`

```{r, echo=FALSE, warning=FALSE, message=FALSE, results=FALSE}
# Fit SEIR model of observed new cases in Ottawa
fit <- fit_seir(
  daily_cases = ott_observed_covid$observed_new_episodes,
  samp_frac_fixed = samp_frac, 
  f_seg = f_seg,
  i0_prior = c(log(7), 1), # 7 total cases on March 1st, 2020
  e_prior = c(0.85, 0.05), # 85% of residents social distancing
  start_decline_prior = c(log(24), 0.1), # Starting date of closing of non-essential businesses (March 24th, 2020)
  end_decline_prior = c(log(34), 0.1), # 10 day buffer to ramp in social distancing
  f_prior = cbind(c(0.4, 0.5, 0.6), c(0.2, 0.2, 0.2)),
  R0_prior = c(log(2.5), 0.2), # Starting R0 value
  N_pop = 1049486, # Ottawa population
  iter = 500, # number of posterior samples
  fit_type = "optimizing" # for speed only
)
```
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Visualize model fit
proj <- project_seir(fit, iter = 1:50)
tidy_proj <- tidy_seir(proj, resample_y_rep = 20)
first_day <- min(ott_observed_covid$date)
last_day <- 500 # how many days to create dates for
lut <- tibble(
  day = seq_len(last_day),
  date = seq(first_day, first_day + length(day) - 1, by = "1 day")
)
tidy_proj <- left_join(tidy_proj, lut, by = "day")
case_projection_plot(tidy_proj, obs_dat = ott_observed_covid, current_col = current_hex,
  value_column = "observed_new_episodes", date_column = "date", title = "Observed daily COVID-19 cases in Ottawa")
```
*Shaded area represents the 95% credible region

## Projected case data
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Generate projections for SEIR model fit
ott_case_projections <- proj_generation(fit, lut, days_project = 60, day_start_reduction = 7, pct_change = 10)

# Create data set to visualize projections
projection_data <- case_projection_data(ott_case_projections)

# Visualize projections
case_projection_plot(projection_data, ott_observed_covid, current_col = current_hex, reduction_col = reduction_hex, increase_col = increase_hex, value_column = "observed_new_episodes", date_column = "date", title = "Projected daily COVID-19 cases in Ottawa", pct_change = 10)
```
*Shaded area represents the 95% credible region