---
title: "Hospital historic projections performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# load library, packages, functions, data
library(tidyverse)
library(ggplot2)
library(EpiNow2)
library(stringr)
library(purrr)
library(lubridate)
library(plotly)
library(RColorBrewer)
library(zoo)
source("../../R/epinow_functions.R")
source("../../R/observed_data.R")
ott_covid_data <- read.csv(file.path(getwd(), "../../Data/Observed data/OPH_Observed_COVID_Data.csv"))

load("../../Model Validation/ww_projections_development/Data/ottawa_historic_hosp_proj_delay_0.RData")
load("../../Data/short_term_hosp_proj.RData")
```

## Current Hospital Projections

```{r, echo=FALSE, warning=FALSE, message=FALSE}
short_term_plot(
  projections = hosp_proj,
  obs_data = ott_covid_data,
  obs_column = "observed_census_ICU_p_acute_care",
  forecast_type = "reported_cases",
  ylab = "Hospital census",
  title = "Projections for hospital census"
)
```

## Historic Hospital Projections 

```{r, echo=FALSE, warning=FALSE, message=FALSE}
signal_col <- "rgb(226, 127, 88)"
proj_col <- "rgb(0, 128, 128)"
proj_shade <- "rgba(0, 128, 128, 0.2)"

hosp_proj_call <- list(type = "avg_data", y_column = "median", name = "Historic projected hospital cases", short_name = "projections", color = proj_col, width = 4, showlegend = TRUE)
hosp_obs_call <- list(type = "observed_data", y_column = "observed_census_ICU_p_acute_care", name = "Observed historic hospital cases", short_name = "Daily signal", color = signal_col, opacity = 0.5)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[1]][["date"]])), paste("to", last(hosp_data_forecast[[1]][["date"]])))), data = hosp_data_forecast[[1]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[2]][["date"]])), paste("to", last(hosp_data_forecast[[2]][["date"]])))), data = hosp_data_forecast[[2]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[3]][["date"]])), paste("to", last(hosp_data_forecast[[3]][["date"]])))), data = hosp_data_forecast[[3]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[4]][["date"]])), paste("to", last(hosp_data_forecast[[4]][["date"]])))), data = hosp_data_forecast[[4]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[5]][["date"]])), paste("to", last(hosp_data_forecast[[5]][["date"]])))), data = hosp_data_forecast[[5]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[6]][["date"]])), paste("to", last(hosp_data_forecast[[6]][["date"]])))), data = hosp_data_forecast[[6]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[7]][["date"]])), paste("to", last(hosp_data_forecast[[7]][["date"]])))), data = hosp_data_forecast[[7]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[8]][["date"]])), paste("to", last(hosp_data_forecast[[8]][["date"]])))), data = hosp_data_forecast[[8]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[9]][["date"]])), paste("to", last(hosp_data_forecast[[9]][["date"]])))), data = hosp_data_forecast[[9]], ticks = FALSE)
```

---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_proj_call, hosp_obs_call), error_bands = TRUE, error_data = c("upper_90", "lower_90"), error_col = proj_shade, titles = c(y = "Hospital cases", x = "Date", title = paste(paste("Hospital projections vs observed cases for", first(hosp_data_forecast[[10]][["date"]])), paste("to", last(hosp_data_forecast[[10]][["date"]])))), data = hosp_data_forecast[[10]], ticks = FALSE)
```