---
title: "Short-term case projections for Ottawa (development page)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Short term projections

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# load library, packages, functions, data
library(EpiNow2)
library(tidyverse)
library(ggplot2)
source("../../R/epinow_functions.R")
ott_covid_data <- read.csv(file.path(getwd(), "../../Data/Observed Data/OPH_Observed_COVID_Data.csv"))
load("../../Data/short_term_forecast.RData")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# visualize epinow forecast
short_term_plot(
  projections = ott_short_forecast,
  obs_data = ott_covid_data,
  forecast_type = "infections",
  ylab = "New cases",
  title = "Projections for new cases by episode date"
)

short_term_plot(
  projections = ott_short_forecast,
  obs_data = ott_covid_data,
  forecast_type = "reported_cases",
  ylab = "New cases",
  title = "Projections for new cases by reported date"
)

short_term_plot(
  projections = ott_short_forecast,
  obs_data = ott_covid_data,
  forecast_type = "R",
  ylab = "Reproduction number",
  title = "Reproduction number projections"
)
```