---
title: "Ottawa wastewater analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# libraries
library(plotly)
library(tidyverse)
library(jsonlite)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stats)

# scripts
source("../../R/lag_replacement.R")
source("../../R/observed_data.R")
source("../../R/data_conversion.R")
source("../../R/hosp_projections.R")
source("../../R/open_ottawa_scripts.R")
source("../../R/wastewater.R")

# Pull JSON objects from OpenOttawa
ottawa_case_data <-
  fromJSON("https://opendata.arcgis.com/datasets/6bfe7832017546e5b30c5cc6a201091b_0/FeatureServer/0/query?where=1%3D1&outFields=Cumulative_Active_Cases_by_Episode_Date,7-day_Average_of_Newly_Reported_cases_by_Reported_Date,Daily_Cases_Linked_to_a_Community_Outbreak_by_Episode_Date,Daily_Cases_Not_Linked_to_an_Outbreak_ie_Sporadic_Cases_by_Episode_Date,Daily_Cases_Linked_to_an_Institutional_Outbreak_by_Episode_Date,Cumulative_Deaths_by_Date_of_Death,_Date,Daily_Cases_by_Reported_Date,Daily_Cases_by_Episode_Date,Cases_Newly_Admitted_to_Hospital,Cases_Currently_in_Hospital,Cases_Currently_in_ICU&outSR=4326&f=json")
ottawa_test_data <-
  fromJSON("https://opendata.arcgis.com/datasets/26c902bf1da44d3d90b099392b544b81_0/FeatureServer/0/query?where=1%3D1&outFields=_Date,Number_of_Tests,Daily_%_Positivity&outSR=4326&f=json")

# data
ott_observed_covid <- data_creation(ottawa_case_data, ottawa_test_data)[["data"]]
ott_observed_waste <- read.csv("../../Data/Observed data/Ottawa_Wastewater_Data.csv")

# functions to integrate waste & covid data together
waste_clean <- wastewater_prep(ott_observed_waste)
ott_covid_waste <- merge_data(ott_observed_covid, waste_clean)

# Colours
case_col <- "rgb(72, 137, 194)"
n1_col <- "rgb(23, 63, 95)"
n2_col <- "rgb(60, 174, 163)"
n1_n2_col <- "rgb(237, 85, 59)"
rolling_avg_col <- "rgb(243, 213, 86)"
```

### Observed Data
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Initialize calls for each parameter
new_case_call <- list(type = "observed_data", y_column = "observed_new_cases", name = "Daily reported new cases", color = case_col)

hosp_call <- list(type = "observed_data", y_column = "observed_census_ICU_p_acute_care", name = "Hospital census", color = case_col)

active_case_call <- list(type = "observed_data", y_column = "observed_active_cases", name = "Active cases", color = case_col)

n1_call <- list(type = "signal_data", y_column = "N1", name = "N1 RNA signal", color = n1_col, yaxis = "y2") 

n2_call <- list(type = "signal_data", y_column = "N2", name = "N2 RNA signal", color = n2_col, yaxis = "y2")

n1_n2_call <- list(type = "avg_data", y_column = "N1_N2_avg", name = "Avg. viral signal", color = n1_n2_col, yaxis = "y2")

rolling_avg_call <- list(type = "avg_data", y_column = "rolling_avg", name = "5-day rolling avg. viral signal", color = rolling_avg_col, yaxis = "y2")
```

Data to `r as.character(tail(ott_covid_waste$date, n=1))`

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(new_case_call), yaxis2 = list(n1_n2_call), titles = c(y = "# of reported new cases", y2 = "Copies per Copies PMMV", x = "Date", title = "Average COVID-19 viral signal in wastewater with respect to daily new cases"), data = ott_covid_waste)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(active_case_call), yaxis2 = list(n1_n2_call), titles = c(y = "# of active cases", y2 = "Copies per Copies PMMV", x = "Date", title = "Average COVID-19 viral signal in wastewater with respect to active cases"), data = ott_covid_waste)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
reworked_figure(xaxis = "date", yaxis = list(hosp_call), yaxis2 = list(n1_n2_call), titles = c(y = "# of patients", y2 = "Copies per Copies PMMV", x = "Date", title = "Average COVID-19 viral signal in wastewater with respect to hospital census"), data = ott_covid_waste)
```

