# This is a workflow to automate the dataset creation for 613covid.ca and
# run short-term hospitalization projections

name: Dataset-creation

# Runs everyday at 2:30pm EST/EDT (7:30pm UTC)
on:
  schedule:
    - cron: "30 19 * * *"
  workflow_dispatch:

jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.3"
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            libcurl4-openssl-dev \
            libtbb-dev \
            libnode-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff-dev \
            libjpeg-dev
          echo "LD_PRELOAD=$(ldconfig -p | grep -m1 'libtbb.so' | awk '{print $NF}')" >> $GITHUB_ENV

      - name: Set compiler flags for RcppParallel
        run: |
          mkdir -p ~/.R
          echo "CXX14FLAGS += -D__TBB_SUPPRESS_DEPRECATED_MESSAGES=1" >> ~/.R/Makevars

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Download variant sheet from Google Drive
        run: curl -L "https://docs.google.com/spreadsheets/d/1jUAWx9_r7CLhh5vtRNNjCRDMX4nEKEx5gvXM_tpsxhE/export?gid=0&format=xlsx" --output "Data/variant_sheet.xlsx" --create-dirs

      - name: Prepare data
        run: Rscript R/dataset_creation.R

      - name: Run short term ww projections 
        run: Rscript R/short_term_ww_projections.R  

      - name: Commit and push files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update projections" -a || echo "Nothing to update"
          git push origin master

